### ISSUE TITLE
Link isn't rendered

### ISSUE THREAD

**Issue by perritoMedia** [Matthew-Wise/umbraco-forms-rte#1]
I've installed the latest nuget package against Umbraco 7.13.1 and Forms 7.0.5.

I can select an internal link or type in an external link but in the RTE, nothing is rendered.

I see the following error in the console 'Could not find the tree packager, activeTree has not been set' - not sure if it's related.

**Comment by Matthew-Wise** [comment]
Hi Alicia,

Thanks for raising this I will take a look at fixing this, hopefully it wont be to long of a wait.

Matt

**Comment by Matthew-Wise** [comment]
As this is for v7 and I have been lazy, I am going to close this issue sorry.
