### ISSUE TITLE
Version 8

### ISSUE THREAD

**Issue by meregan** [Matthew-Wise/umbraco-forms-rte#2]
Hi

I get a 404 for umbraco/rte in version 8, any ideas why that would be?

**Comment by Matthew-Wise** [comment]
I have not tested this for V8. I would guess the changes in V8 have broken something.

Right now I won't have the time to look into the issue.

**Comment by meregan** [comment]
No problem, will see what i can figure out and let you know.

**Comment by AndersBrohus-MySupport** [comment]
Did you find a solution to the problem? :)

**Comment by Matthew-Wise** [comment]
Currently an open PR for this #6 so hopefully I will release an update soon.

Matt

**Comment by Matthew-Wise** [comment]
v8 is now released links to our and Nuget are on the read me 🎉
