### ISSUE TITLE
RTE form field doesn't respond to conditional display

### ISSUE THREAD

**Issue by leadmonkeyboy** [Matthew-Wise/umbraco-forms-rte#3]
When I attempt to display the RTE conditionally it doesn't appear to work properly (it never displays even when the condition is met)

![image](https://user-images.githubusercontent.com/17127434/64743874-6713d480-d4b6-11e9-864f-eeaa6888c767.png)

**Comment by Sam7** [comment]
Yes, I found the same issue. If someone could point me in the right direction in regards to documentation on conditions etc. I'd be happy to put in a pull request. I can't seem to find anything here: https://our.umbraco.com/documentation/Add-ons/umbracoforms/developer/extending/

**Comment by Matthew-Wise** [comment]
Should be a new release in the next week with a fix for this in the mean time you can patch it with the fix here - https://our.umbraco.com/packages/backoffice-extensions/umbraco-forms-rich-text/umbraco-forms-rich-text-help/96600-rich-text-not-displaying-with-conditional-statement

**Comment by Matthew-Wise** [comment]
FYI this is fixed for the v8 version. I will see about getting v7 updated..
